version: 0.2

environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-7-openjdk-amd64"

phases:
  install:
    commands:
      - apt-get update -y
        - apt-get install default-jdk -y
        - apt-get install -y maven
    runtime-versions:
      java: openjdk7
  build:
    commands:
      - mvn clean package --quiet
artifacts:
  discard-paths: yes
  files:
    - target/*
    - scripts/*
    - appspec.yml
